[profile.default]
src = 'src'
out = 'out'
script = 'script'
libs = ['lib']
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200
solc = '0.8.27'
bytecode_hash = 'none'
fuzz = { runs = 10000 }

[profile.ci.fuzz]
runs = 100000
seed = "0x640"

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}